{
printf("<?xml version=\"1.0\"?>\n");
printf("<BlastOutput>\n");
printf("  <BlastOutput_program>blastn</BlastOutput_program>\n");
printf("  <BlastOutput_version>BLASTN 2.2.25+</BlastOutput_version>\n");
printf("  <BlastOutput_reference>Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&amp;auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), &quot;Gapped BLAST and PSI-BLAST: a new generation of protein database search programs&quot;, Nucleic Acids Res. 25:3389-3402.</BlastOutput_reference>\n");
printf("  <BlastOutput_db>n/a</BlastOutput_db>\n");
printf("  <BlastOutput_query-ID>%s</BlastOutput_query-ID>\n",$1);
printf("<BlastOutput_iterations>\n");
printf("<Iteration>\n");
printf("  <Iteration_iter-num>1</Iteration_iter-num>\n");
printf("  <Iteration_query-len>%s</Iteration_query-len>\n",$3);
printf("<Iteration_hits>\n");
printf("<Hit>\n");
printf("  <Hit_num>%d</Hit_num>\n",hit_num++);
printf("  <Hit_def>%s</Hit_def>\n",$2);
printf("  <Hit_len>?</Hit_len>\n");
printf("  <Hit_hsps>\n");
printf("    <Hsp>\n");
printf("      <Hsp_num>1</Hsp_num>\n");
printf("      <Hsp_bit-score>159.983</Hsp_bit-score>\n");
printf("      <Hsp_score>176</Hsp_score>\n");
printf("      <Hsp_evalue>9.34813e-45</Hsp_evalue>\n");
printf("      <Hsp_query-from>%s</Hsp_query-from>\n",$5);
printf("      <Hsp_query-to>%s</Hsp_query-to>\n",$6);
printf("      <Hsp_hit-from>%s</Hsp_hit-from>\n",$7);
printf("      <Hsp_hit-to>%s</Hsp_hit-to>\n",$8);
printf("      <Hsp_query-frame>???</Hsp_query-frame>\n");
printf("      <Hsp_hit-frame>??</Hsp_hit-frame>\n");
printf("      <Hsp_identity>??</Hsp_identity>\n");
printf("      <Hsp_positive>??</Hsp_positive>\n");
printf("      <Hsp_gaps>?</Hsp_gaps>\n");
printf("      <Hsp_align-len>?</Hsp_align-len>\n");
printf("    </Hsp>\n");
printf("  </Hit_hsps>\n");
printf("</Hit>\n");
printf("</Iteration_hits>\n");
printf("</Iteration>\n");
printf("</BlastOutput_iterations>\n");
printf("</BlastOutput>\n");
}
